name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Use poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: latest
      - name: Install dependencies
        run: poetry install --with dev,test
      - name: Run ruff check
        run: poetry run ruff check .
      - name: Run ruff format
        run: poetry run ruff format --check .
      - name: Run mypy
        run: poetry run mypy .
      - name: Test with pytest
        run: poetry run pytest
